apiVersion: v1
kind: ConfigMap
metadata:
  name: hivagold-config
  namespace: hivagold
data:
  ENVIRONMENT: development
  APP_VERSION: "1.0.0"

  AUTH_WORKER_URL: http://bot-auth-worker:8002
  TRADING_WORKER_URL: http://bot-trading-worker:8006
  PORTFOLIO_WORKER_URL: http://bot-simulator-worker:8007
  CAPTCHA_SOLVE_URL: http://bot-captcha-worker:8001/solve

  BASE_DOMAIN: https://hivagold.com
  DEFAULT_MARKET: xag
  HIVAGOLD_TENANT_ID: "11111"
  USERS_STORAGE_DIR: ../bot_auth_worker/Users
