apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hivagold
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - bot-captcha-worker.yaml
  - bot-auth-worker.yaml
  - bot-simulator-worker.yaml
  - api-server.yaml
  - ingress.yaml
  - externalname-services.yaml
